### ISSUE TITLE
[BUG] Dataset false reports

### ISSUE THREAD

**Issue by ia-mbordyukov** [ia-eknorr/ignition-lint#31]
**Describe the bug**
  Parameter keys should be in camelCase:
    - view.custom.dataset.$
    - view.custom.dataset.$columns
example:
https://github.com/inductive-automation/demo-vertical-datacenter/actions/runs/8824835123/job/24228033135

**To Reproduce**
Save a dataset property

**Expected behavior**
No errors

**Comment by ia-eknorr** [comment]
#34 closes this issue. Will be released in v2.1 soon.
